#!/usr/bin/env bash

export USER_ID=$(id -u)
export GROUP_ID=$(id -g)

export LD_PRELOAD=libnss_wrapper.so
export NSS_WRAPPER_PASSWD=/tmp/passwd
export NSS_WRAPPER_GROUP=/etc/group

if [ ! -f /tmp/passwd ]; then
    envsubst < /usr/local/share/passwd.template > /tmp/passwd
fi


/bin/sh -c "$@"
