version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.06.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: apk add --no-cache make bash
      - run:
          name: Build Docker images
          command: make
      - deploy:
          name: Push Docker images
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
              docker push syndesis/go-18-centos7
            fi
